### ISSUE TITLE
interpreter: unreachable state at address 0x754d76

### ISSUE THREAD

**Issue by Waterman178** [airbus-seclab/bincat#77]
```
INFO:bincat.gui:Launching the analyzer
WARNING:bincat.gui:This file format is not natively supported byBinCAT, you should probably remap the binary.
INFO:bincat.plugin:Current analyzer path: c:\users\admini~1\appdata\local\temp\tmpirlta9bincat
ERROR:bincat.plugin.npkgen:Error encountered while running gcc. Is it installed in PATH?
WARNING:bincat.plugin:Could not compile header file, types from IDB will not be used for type propagation
WARNING:bincat.plugin:.no file containing type data for the file being analyzed could not be generated, continuing. The ida-generated header could be invalid.
INFO:bincat.plugin:Analyzer: starting process
INFO:bincat.plugin:Analyzer started.
INFO:bincat.plugin:Analyzer process finished
INFO:bincat.plugin:---- stdout ----------------
INFO:bincat.plugin:BinCAT v0.9

INFO:bincat.plugin:---- stderr ----------------
INFO:bincat.plugin:
INFO:bincat.plugin:---- logfile ---------------
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: at S0x18e2fc: inferred type is ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x44541a
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x44541a: [89 48 0c c7 00 dc 82 c4 00 c3 90 90 90 90 90 90]
INFO:bincat.plugin:[TRACE] 0x44541a: [ (32)[(eax + SignExtension (32) 0xc)] <- ecx; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(ecx)
INFO:bincat.plugin:[DEBUG] unrel: span_taint(ecx) v=0x0
INFO:bincat.plugin:[INFO2] unrel: (set) (32)[(eax + SignExtension (32) 0xc)] = ecx (0x0)
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((eax + SignExtension (32) 0xc))
INFO:bincat.plugin:[DEBUG] unrel: write_in_mem (S0x18e300, 0x0, 32)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type (32)[(eax + SignExtension (32) 0xc)] ?
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((eax + SignExtension (32) 0xc))
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: at S0x18e300: inferred type is ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x44541d
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x44541d: [c7 00 dc 82 c4 00 c3 90 90 90 90 90 90 90 90 90]
INFO:bincat.plugin:[TRACE] 0x44541d: [ (32)[eax] <- 0xc482dc; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(0xc482dc)
INFO:bincat.plugin:[DEBUG] unrel: span_taint(0xc482dc) v=0xc482dc
INFO:bincat.plugin:[INFO2] unrel: (set) (32)[eax] = 0xc482dc (0xc482dc)
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(eax)
INFO:bincat.plugin:[DEBUG] unrel: write_in_mem (S0x18e2f4, 0xc482dc, 32)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type (32)[eax] ?
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(eax)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: at S0x18e2f4: inferred type is ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x445423
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x445423: [c3 90 90 90 90 90 90 90 90 90 90 90 90 8b 44 24]
INFO:bincat.plugin:[TRACE] 0x445423: [ ret,
INFO:bincat.plugin:[TRACE] 0x445423: esp <- (esp + 0x4); ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((32)[esp])
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value : S0x18e2b4 32
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value result : 0x754d52
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((esp + 0x4))
INFO:bincat.plugin:[DEBUG] unrel: span_taint((esp + 0x4)) v=S0x18e2b8
INFO:bincat.plugin:[INFO2] unrel: (set) esp = (esp + 0x4) (S0x18e2b8)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type esp ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x754d52
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x754d52: [c7 44 24 18 60 9c c6 00 c7 44 24 1c 4f 00 00 00]
INFO:bincat.plugin:[TRACE] 0x754d52: [ (32)[(esp + 0x18)] <- 0xc69c60; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(0xc69c60)
INFO:bincat.plugin:[DEBUG] unrel: span_taint(0xc69c60) v=0xc69c60
INFO:bincat.plugin:[INFO2] unrel: (set) (32)[(esp + 0x18)] = 0xc69c60 (0xc69c60)
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((esp + 0x18))
INFO:bincat.plugin:[DEBUG] unrel: write_in_mem (S0x18e2d0, 0xc69c60, 32)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type (32)[(esp + 0x18)] ?
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((esp + 0x18))
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: at S0x18e2d0: inferred type is ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x754d5a
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x754d5a: [c7 44 24 1c 4f 00 00 00 8a 44 24 5c 8b 8d d8 02]
INFO:bincat.plugin:[TRACE] 0x754d5a: [ (32)[(esp + 0x1c)] <- 0x4f; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(0x4f)
INFO:bincat.plugin:[DEBUG] unrel: span_taint(0x4f) v=0x4f
INFO:bincat.plugin:[INFO2] unrel: (set) (32)[(esp + 0x1c)] = 0x4f (0x4f)
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((esp + 0x1c))
INFO:bincat.plugin:[DEBUG] unrel: write_in_mem (S0x18e2d4, 0x4f, 32)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type (32)[(esp + 0x1c)] ?
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((esp + 0x1c))
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: at S0x18e2d4: inferred type is ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x754d62
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x754d62: [8a 44 24 5c 8b 8d d8 02 00 00 8b 15 20 46 de 00]
INFO:bincat.plugin:[TRACE] 0x754d62: [ eax[0, 7] <- (8)[(esp + 0x5c)]; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((8)[(esp + 0x5c)])
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value : S0x18e314 8
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value result : 0x0
INFO:bincat.plugin:[DEBUG] unrel: span_taint((8)[(esp + 0x5c)]) v=0x0
INFO:bincat.plugin:[INFO2] unrel: (set) eax[0, 7] = (8)[(esp + 0x5c)] (0x0)
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((esp + 0x5c))
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type eax[0, 7] ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x754d66
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x754d66: [8b 8d d8 02 00 00 8b 15 20 46 de 00 88 44 24 20]
INFO:bincat.plugin:[TRACE] 0x754d66: [ ecx <- (32)[(ebp + 0x2d8)]; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((32)[(ebp + 0x2d8)])
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value : 0x66e9168 32
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value result : 0x3e3fc90
INFO:bincat.plugin:[DEBUG] unrel: span_taint((32)[(ebp + 0x2d8)]) v=0x3e3fc90
INFO:bincat.plugin:[INFO2] unrel: (set) ecx = (32)[(ebp + 0x2d8)] (0x3e3fc90)
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((ebp + 0x2d8))
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type ecx ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x754d6c
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x754d6c: [8b 15 20 46 de 00 88 44 24 20 89 4c 24 24 89 5c]
INFO:bincat.plugin:[TRACE] 0x754d6c: [ edx <- (32)[0xde4620]; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((32)[0xde4620])
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value : 0xde4620 32
INFO:bincat.plugin:[DEBUG] unrel: 	Not found in mapping, checking sections
INFO:bincat.plugin:== (same line repeated 4 times) ==
INFO:bincat.plugin:[DEBUG] mapped_mem: read byte 00
INFO:bincat.plugin:[DEBUG] unrel: get_mem_value result : 0x0
INFO:bincat.plugin:[DEBUG] unrel: span_taint((32)[0xde4620]) v=0x0
INFO:bincat.plugin:[INFO2] unrel: (set) edx = (32)[0xde4620] (0x0)
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(0xde4620)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type edx ?
INFO:bincat.plugin:[INFO2] interpreter: ################### 0x754d72
INFO:bincat.plugin:[DEBUG] mapped_mem: read 16 bytes at 0x754d72: [88 44 24 20 89 4c 24 24 89 5c 24 54 8b 42 1c 8b]
INFO:bincat.plugin:[TRACE] 0x754d72: [ (8)[(esp + 0x20)] <- eax[0, 7]; ]
INFO:bincat.plugin:[DEBUG] unrel: eval_exp(eax[0, 7])
INFO:bincat.plugin:[DEBUG] unrel: span_taint(eax[0, 7]) v=B0x_
INFO:bincat.plugin:[INFO2] unrel: (set) (8)[(esp + 0x20)] = eax[0, 7] (B0x_)
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: set_type (8)[(esp + 0x20)] ?
INFO:bincat.plugin:[DEBUG] unrel: eval_exp((esp + 0x20))
INFO:bincat.plugin:[DEBUG] reduced_unrel_typenv: at S0x18e2d8: inferred type is ?
INFO:bincat.plugin:[ANALYSIS] interpreter: unreachable state at address 0x754d76
INFO:bincat.plugin:[STOP] stopped after 0x754d72
INFO:bincat.plugin:====== end of logfile ======
INFO:bincat.plugin:Storing analysis results to idb...
INFO:bincat.plugin:Analysis results have been stored idb.
```
![2](https://user-images.githubusercontent.com/14991217/45955454-882fab00-c042-11e8-88e1-df3b4db3cab9.png)
![3](https://user-images.githubusercontent.com/14991217/45955457-8d8cf580-c042-11e8-9b83-27e846e5cb3d.png)
I have set up stack memory. How can this problem arise?

**Comment by phil777** [comment]
Hello,

Could you show us the logs with
```
loglevel = 6
```
in the .ini file ?

Thanks !

**Comment by killpy** [comment]
I set the loglevel to 6 and started running. It stays here all the time.It seems to only support loglevel=5
![qq 20180925112903](https://user-images.githubusercontent.com/14991217/45991243-95867d00-c0b6-11e8-94f5-b3ac6470ab41.png)
![2](https://user-images.githubusercontent.com/14991217/45991250-99b29a80-c0b6-11e8-9e5f-b2286e77e5e8.png)

**Comment by phil777** [comment]
Hello,

The logs were overwhelmed by initialization stuff. It reached 1Mo and it was far from the interesting part.
 
Sorry to ask you to do it again, but could you send us the logs with
```
loglevel = 6
loglevel vector = 5
```

Thanks for your time!

**Comment by killpy** [comment]
ok.here is the file！A little big.I split it into two compression packs.
[01.zip](https://github.com/airbus-seclab/bincat/files/2416031/01.zip)
[02.zip](https://github.com/airbus-seclab/bincat/files/2416041/02.zip)

**Comment by killpy** [comment]
How is it going?

**Comment by phil777** [comment]
Hello,

This was a limitation due to the fact that our model separated stack and global memory. 
Merging stack into global memory was on our agenda for a long time.

Here is an alpha version of this merge in this branch:
https://github.com/airbus-seclab/bincat/tree/no_more_stack

All the `stack[..]` should be replaced with `mem[...]` and the `S` prefix before addresses to indicate the stack region should not be seen anymore.

Note that you'll have to reinstall the plugin.

Let us know if it solved your problem.

**Comment by killpy** [comment]
how to  reinstall the plugin？How to uninstall the old plugin first?

**Comment by phil777** [comment]
Just install the new one again, as you did the first time. It will overwrite the old one.

**Comment by killpy** [comment]
I executed the install_plugin.py script in ida.It did not prompt that the installation was successful.Just output..As shown Then I replaced stack[..] with mem[...].After running the analysis, this error still occurs.But the location of the error is different.
![0](https://user-images.githubusercontent.com/14991217/46147889-4d738000-c299-11e8-8d14-dad6d6caa078.png)
![1](https://user-images.githubusercontent.com/14991217/46148232-2ff2e600-c29a-11e8-83a1-8f3f7b351df7.png)
![2](https://user-images.githubusercontent.com/14991217/46148241-36815d80-c29a-11e8-9d5f-7303cb1840ce.png)
![3](https://user-images.githubusercontent.com/14991217/46148250-3aad7b00-c29a-11e8-8768-bb37ee6ee1f0.png)
![4](https://user-images.githubusercontent.com/14991217/46148259-3d0fd500-c29a-11e8-912f-7d1915788d7b.png)
[analyzer.zip](https://github.com/airbus-seclab/bincat/files/2424211/analyzer.zip)

**Comment by phil777** [comment]
In your .ini file, you may have something like:
```
reg[esp] = S0x18e314
```
Remove the leading `S`:
```
reg[esp] = 0x18e314
```

Also, apparently you are still using the old version, not the branch I pointed you too (However, it is possible that your analysis work with the old version if no reference to a stack region is done in the .ini file).

Let us know :)

**Comment by killpy** [comment]
I did not find something like reg[esp] = S0x18e314 in the init.ini file,but I found some in the out.ini file.I did reinstall the branch.I deleted the bincat0 plugin and re-run the install_plugin.py script.

**Comment by phil777** [comment]
Can you send me the init.ini file ?

**Comment by killpy** [comment]
here is the file:
[init.zip](https://github.com/airbus-seclab/bincat/files/2425138/init.zip)

**Comment by killpy** [comment]
xxxxxxxxxx@xxxxxxxxx0xxxxxx2 ~
$ cd bincat

xxxxxxxxxx@xxxxxxxxx0xxxxxx2 ~/bincat
$  make
Compiling OCaml part.................................................
make[1]: 进入目录“/home/Administrator/bincat/ocaml/src”
ocamlfind: Package `num' not found
[ -f bincat_ver.ml ] || touch bincat_ver.ml
grep -q v0.9 bincat_ver.ml || sed s/XXX/v0.9/ bincat_ver.ml.tmpl > bincat_ver.ml
make -C npk/ BYTECODE=
make[2]: 进入目录“/home/Administrator/bincat/ocaml/src/npk”
ocamlfind: Package `num' not found
ocamlopt -g -w Ael -warn-error +a-3-7-50-42-44-58-26 -unsafe-string  -I C:/OCaml64/home/Administrator/.opam/4.06.1+mingw64c/lib/ocamlgraph  -I C:/OCaml64/home/Administrator/.opam/4.06.1+mingw64c/lib/zarith  -I  -I utils -I newspeak -I c2newspeak  -c version.mli
don't know what to do with utils
Usage: ocamlopt <options> <files>
Options are:
  -fPIC  Generate position-independent machine code (default)
  -fno-PIC  Generate position-dependent machine code
  -a  Build a library
  -absname  Show absolute filenames in error messages
  -afl-instrument Enable instrumentation for afl-fuzz
  -afl-inst-ratio Configure percentage of branches instrumented
     (advanced, see afl-fuzz docs for AFL_INST_RATIO)
  -annot  Save information in <filename>.annot
  -bin-annot  Save typedtree in <filename>.cmt
  -inline-branch-factor <n>|<round>=<n>[,...]  Estimate the probability of a branch being cold as 1/(1+n) (used for inlining) (default 0.10)
  -c  Compile only (do not link)
  -cc <command>  Use <command> as the C compiler and linker
  -cclib <opt>  Pass option <opt> to the C linker
  -ccopt <opt>  Pass option <opt> to the C compiler and linker
  -clambda-checks  Instrument clambda code with closure and field access checks(for debugging the compiler)
  -Oclassic  Make inlining decisions at function definition time rather than atthe call site (replicates previous behaviour of the compiler)
  -color {auto|always|never}  Enable or disable colors in compiler messages
    The following settings are supported:
      auto    use heuristics to enable colors only if supported
      always  enable colors
      never   disable colors
    The default setting is 'auto', and the current heuristic
    checks that the TERM environment variable exists and is
    not empty or "dumb", and that isatty(stderr) holds.
  -compact  Optimize code size rather than speed
  -config  Print configuration values and exit
  -dtypes  (deprecated) same as -annot
  -for-pack <ident>  Generate code that can later be `packed' with
     ocamlopt -pack -o <ident>.cmx
  -g  Record debugging information for exception backtrace
  -i  Print inferred interface
  -I <dir>  Add <dir> to the list of include directories
  -impl <file>  Compile <file> as a .ml file
  -inline <n>|<round>=<n>[,...]  Aggressiveness of inlining (default 1.25, higher numbers mean more aggressive)
  -inline-toplevel <n>|<round>=<n>[,...]  Aggressiveness of inlining at toplevel (higher numbers mean more aggressive)
  -inline-alloc-cost <n>|<round>=<n>[,...]  The cost of not removing an allocation during inlining (default 7, higher numbers more costly)
  -inline-branch-cost <n>|<round>=<n>[,...]  The cost of not removing a conditional during inlining (default 5, higher numbers more costly)
  -inline-call-cost <n>|<round>=<n>[,...]  The cost of not removing a call during inlining (default 5, higher numbers more costly)
  -inline-prim-cost <n>|<round>=<n>[,...]  The cost of not removing a primitiveduring inlining (default 3, higher numbers more costly)
  -inline-indirect-cost <n>|<round>=<n>[,...]  The cost of not removing an indirect call during inlining (default 4, higher numbers more costly)
  -inline-lifting-benefit <n>|<round>=<n>[,...]  The benefit of lifting definitions to toplevel during inlining (default 1300, higher numbers more beneficial)
  -inlining-report  Emit `.<round>.inlining' file(s) (one per round) showing the inliner's decisions
  -intf <file>  Compile <file> as a .mli file
  -intf-suffix <string>  Suffix for interface files (default: .mli)
  -keep-docs  Keep documentation strings in .cmi files
  -no-keep-docs  Do not keep documentation strings in .cmi files (default)
  -keep-locs  Keep locations in .cmi files (default)
  -no-keep-locs  Do not keep locations in .cmi files
  -labels  Use commuting label mode
  -linkall  Link all modules, even unused ones
  -inline-max-depth <n>|<round>=<n>[,...]  Maximum depth of search for inliningopportunities inside inlined functions (default 1)
  -alias-deps  Do record dependencies for module aliases
  -no-alias-deps  Do not record dependencies for module aliases
  -linscan  Use the linear scan register allocator
  -app-funct  Activate applicative functors
  -no-app-funct  Deactivate applicative functors
  -no-float-const-prop  Deactivate constant propagation for floating-point operations
  -noassert  Do not compile assertion checks
  -noautolink  Do not automatically link C libraries specified in .cmxa files
  -nodynlink  Enable optimizations for code that will not be dynlinked
  -nolabels  Ignore non-optional labels in types
  -nostdlib  Do not add default directory to the list of include directories
  -no-unbox-free-vars-of-closures  Do not unbox variables that will appear inside function closures
  -no-unbox-specialised-args  Do not unbox arguments to which functions have been specialised
  -o <file>  Set output file name to <file>
  -O2  Apply increased optimization for speed
  -O3  Apply aggressive optimization for speed (may significantly increase codesize and compilation time)
  -opaque  Does not generate cross-module optimization information
     (reduces necessary recompilation on module change)
  -open <module>  Opens the module <module> before typing
  -output-obj  Output an object file instead of an executable
  -output-complete-obj  Output an object file, including runtime, instead of anexecutable
  -p  Compile and link with profiling support for "gprof"
     (not supported on all platforms)
  -pack  Package the given .cmx files into one .cmx
  -plugin <plugin>  Load dynamic plugin <plugin>
  -pp <command>  Pipe sources through preprocessor <command>
  -ppx <command>  Pipe abstract syntax trees through preprocessor <command>
  -principal  Check principality of type inference
  -no-principal  Do not check principality of type inference (default)
  -rectypes  Allow arbitrary recursive types
  -no-rectypes  Do not allow arbitrary recursive types (default)
  -remove-unused-arguments  Remove unused function arguments
  -rounds <n>  Repeat tree optimization and inlining phases this many times (default 1).  Rounds are numbered starting from zero.
  -runtime-variant <str>  Use the <str> variant of the run-time system
  -S  Keep intermediate assembly file
  -safe-string  Make strings immutable (default)
  -shared  Produce a dynlinkable plugin
  -short-paths  Shorten paths in types
  -strict-sequence  Left-hand part of a sequence must have type unit
  -no-strict-sequence  Left-hand part of a sequence need not have type unit (default)
  -strict-formats  Reject invalid formats accepted by legacy implementations
     (Warning: Invalid formats may behave differently from
      previous OCaml versions, and will become always-rejected
      in future OCaml versions. You should always use this flag
      to detect invalid formats so you can fix them.)
  -no-strict-formats  Accept invalid formats accepted by legacy implementations(default)
     (Warning: Invalid formats may behave differently from
      previous OCaml versions, and will become always-rejected
      in future OCaml versions. You should never use this flag
      and instead fix invalid formats.)
  -thread  Generate code that supports the system threads library
  -unbox-closures  Pass free variables via specialised arguments rather than closures
  -unbox-closures-factor <n > 0>  Scale the size threshold above which unbox-closures will slow down indirect calls rather than duplicating a function (default10)
  -inline-max-unroll <n>|<round>=<n>[,...]  Unroll recursive functions at most this many times (default 0)
  -unboxed-types  unannotated unboxable types will be unboxed
  -no-unboxed-types  unannotated unboxable types will not be unboxed (default)
  -unsafe  Do not compile bounds checking on array and string access
  -unsafe-string  Make strings mutable
  -v  Print compiler version and location of standard library and exit
  -verbose  Print calls to external commands
  -version  Print version and exit
  --version  Print version and exit
  -vnum  Print version number and exit
  -w <list>  Enable or disable warnings according to <list>:
        +<spec>   enable warnings in <spec>
        -<spec>   disable warnings in <spec>
        @<spec>   enable warnings in <spec> and treat them as errors
     <spec> can be:
        <num>             a single warning number
        <num1>..<num2>    a range of consecutive warning numbers
        <letter>          a predefined set
     default setting is "+a-4-6-7-9-27-29-32..42-44-45-48-50-60"
  -warn-error <list>  Enable or disable error status for warnings according
     to <list>.  See option -w for the syntax of <list>.
     Default setting is "-a+31"
  -warn-help  Show description of warning numbers
  -where  Print location of standard library and exit
  - <file>  Treat <file> as a file name (even if it starts with `-')
  -nopervasives  (undocumented)
  -dsource  (undocumented)
  -dparsetree  (undocumented)
  -dtypedtree  (undocumented)
  -drawlambda  (undocumented)
  -dlambda  (undocumented)
  -drawclambda  (undocumented)
  -dclambda  (undocumented)
  -dflambda  Print Flambda terms
  -drawflambda  Print Flambda terms after closure conversion
  -dflambda-no-invariants  Do not Check Flambda invariants around each pass
  -dflambda-let <stamp>  Print when the given Flambda [Let] is created
  -dflambda-verbose  Print Flambda terms including around each pass
  -dcmm  (undocumented)
  -dsel  (undocumented)
  -dcombine  (undocumented)
  -dcse  (undocumented)
  -dlive  (undocumented)
  -davail  Print register availability info when printing liveness
  -drunavail  Run register availability pass (for testing only; needs -g)
  -dspill  (undocumented)
  -dsplit  (undocumented)
  -dinterf  (undocumented)
  -dprefer  (undocumented)
  -dalloc  (undocumented)
  -dreload  (undocumented)
  -dscheduling  (undocumented)
  -dlinear  (undocumented)
  -dinterval  (undocumented)
  -dstartup  (undocumented)
  -dtimings  Print timings information for each pass
  -dprofile  Print performance information for each pass
    The columns are: time alloc top-heap absolute-top-heap.
  -dump-pass  Record transformations performed by these passes:
     unbox-closures unbox-specialised-args unbox-free-vars-of-closures
     remove-free-vars-equal-to-args remove-unused-arguments unused-arguments
  -args <file> Read additional newline-terminated command line arguments
      from <file>
  -args0 <file> Read additional null character terminated command line arguments
from <file>
  -depend <options> Compute dependencies (use 'ocamlopt -depend -help' for details)
  -help  Display this list of options
  --help  Display this list of options
make[2]: *** [Makefile:145：version.cmi] 错误 2
make[2]: 离开目录“/home/Administrator/bincat/ocaml/src/npk”
make[1]: *** [Makefile:179：npk/newspeak.cmxa] 错误 2
make[1]: 离开目录“/home/Administrator/bincat/ocaml/src”
make: *** [Makefile:20：all] 错误 2

xxxxxxxxxx@xxxxxxxxx0xxxxxx2 ~/bincat
$
The script run by ida may still be an old version，because it seem to need to compile the branch code first.I forgot to compile the branch script code first.I followed this tutorial and installed it. I started compiling. It prompts these errors above.what happened?
https://github.com/airbus-seclab/bincat/blob/master/doc/windows_build.md

**Comment by killpy** [comment]
I have compiled it.But there was a lot of mistakes.I don't know what's wrong.

**Comment by killpy** [comment]
I have installed all the packages.But these errors occur
![qq 20180928205758](https://user-images.githubusercontent.com/14991217/46209788-5f205a80-c361-11e8-8015-9c512c23894a.png)

**Comment by phil777** [comment]
Apprently, for recent ocaml, you need this too:
```
opam install num
```

**Comment by killpy** [comment]
Some errors occurred while executing the makefile.I found a problem with the ldd command.Why ida can view the dependent library of bincat.exe?However, ldd cannot display this dependent library (libgmp-10.dll) 
![qq 20180929071642](https://user-images.githubusercontent.com/14991217/46237724-f82e9000-c3b8-11e8-8610-eb25dfb91cd4.png)
![qq 20180929071606](https://user-images.githubusercontent.com/14991217/46237730-febd0780-c3b8-11e8-8397-47cf35848674.png)
![qq 20180929071543](https://user-images.githubusercontent.com/14991217/46237733-01b7f800-c3b9-11e8-9d2b-39cf4dab6e7c.png)


Please see the picture

**Comment by killpy** [comment]
The problem has been solved.thanks!But there are new problems.It seems that the bincat can not execute API?When it executes the API function InterlockedExchange,it prompts the existence of the lock instruction.
![1](https://user-images.githubusercontent.com/14991217/46246401-4c745700-c42f-11e8-8ad5-f64f465f335f.png)
![2](https://user-images.githubusercontent.com/14991217/46246404-50a07480-c42f-11e8-88c5-894232acac2f.png)

**Comment by phil777** [comment]
Hello,

It stops because we did not implement the LOCK prefix.

Here is a branch that includes a patch to ignore this prefix (we don't support multi-threading yet anyway):

https://github.com/airbus-seclab/bincat/tree/issue77

You'll have to clone this branch, recompile and reinstall bincat, but you don't have to reinstall the IDA plugin this time.

**Comment by trou** [comment]
Syscalls and external library calls can/should be stubbed through imports, (see `stubs.ml`).
